name: Deploy to EC2

on:
  push:
    branches:
      - assignment-3
    tags:
      - 'deploy-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get environment from tag
        id: get-environment
        run: |
          ENVIRONMENT=$(echo ${GITHUB_REF#refs/*/} | cut -d '-' -f 2)
          echo "::set-output name=environment::$ENVIRONMENT"

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.3'

      - name: Apply Terraform configuration
        run: |
          echo "environment = \"${{ steps.get-environment.outputs.environment }}\"" > terraform.tfvars
          terraform init
          curl -f http://$(terraform output -raw ec2_public_ip):80
        working-directory: ./terraform
