name: Deploy to EC2

on:
  push:
    branches:
      - assignment-3
    tags:
      - 'deploy-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-output: json

      - name: Get environment from tag
        id: get-environment
        run: |
          ENVIRONMENT=$(echo ${GITHUB_REF#refs/*/} | cut -d '-' -f 2)
          echo "::set-output name=environment::$ENVIRONMENT"

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.3'

      - name: Apply Terraform configuration
        run: |
          echo "environment = \"${{ steps.get-environment.outputs.environment }}\"" > terraform.tfvars
          terraform init
          terraform plan
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
   
      - name: Validate app health
        run: |
          curl -f http://$(terraform output -raw ec2_public_ip):80
