name: destroy the infrastructure

on:
  push:
    paths:
      - '.github/workflows/destroy.yml'       # Trigger when files current file edited change
    branches:
      - assignment-3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Apply destroy configuration
        run: |
          terraform destroy --auto-approve
        working-directory: ./terraform
