name: destroy the infrastructure

on:
  push:
    paths:
      - '.github/workflows/destroy.yml'       # Trigger when files current file edited change
    branches:
      - assignment-3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.3'

      - name: Apply destroy configuration
        run: |
          terraform destroy --auto-approve
        working-directory: ./terraform

